### ISSUE TITLE
niet alleen /def en /id gebruiken maar ook /doc

### ISSUE THREAD

**Issue by NielsHoffmann** [Geonovum/uri-bp#3]
In de best practice wordt het gebruik van /def (voor concepten / definities) en /id voor individuals besproken, maar niet het gebruik van /doc (documentatie / metadata) van het object in het register beschreven.

Als je kijkt naar de basisregistraties, dan wordt daar dus een onderscheid gemaak tussen het individu (http://bgt.basisregistraties.overheid.nl/bgt/id/Wegdeel/G0034.000121f2ca714be3a6a0d091bdd43d6e) en de documentatie over dat individu (lv-publicatiedatum, bronhouder, tijdstipregistratie) op de /doc uri
http://bgt.basisregistraties.overheid.nl/bgt/doc/Wegdeel/G0034.000121f2ca714be3a6a0d091bdd43d6e

**Comment by StichtingRIONED** [comment]
Bedankt Niels. We hebben je suggestie meegenomen in de laatste update.

**Comment by NielsHoffmann** [comment]
gezien dat de opmerking is meegenomen in de laatste update. Daarmee kan het issue gesloten worden.
