### ISSUE TITLE
{owner} in uri of niet...

### ISSUE THREAD

**Issue by NielsHoffmann** [Geonovum/uri-bp#4]
In de review commentaren (inclusief mijn eigen commentaar) wordt gesteld dat {owner} niet handig is om expliciet op te nemen in de uri. Tegelijkertijd zien we dat in het nen3610-id wel ook een bronhouder identificatie opgenomen wordt.
Ik denk dat je hier misschien wel naar moet kijken vanuit het oogpunt van de praktische haalbaarheid van het genereren van unieke resources.
 
Aan de ene kant zou je een 'ID uitgifte service' kunnen inrichten bij Rioned waar elke organisatie die een individu wil opvoeren een PID (Persistent ID) kan opvragen. Of dit handig en schaalbaar is kun je je afvragen.
Het andere 'model' is dat een organisatie zelf een PID kan aanmaken, waar dan een organisatie code in voorkomt (om het ID uniek te maken). ( zoals bronhouder code BGT bv). Hiermee kun je 'gedistribueerde unieke PID's' aanmaken. De betekenis van die organisatie code is dan niet automatisch 'owner' van het individu maar slechts de initiator van het PID...

**Comment by redmer** [comment]
> Het andere 'model' is dat een organisatie zelf een PID kan aanmaken, waar dan een organisatie code in voorkomt (om het ID uniek te maken). ( zoals bronhouder code BGT bv). Hiermee kun je 'gedistribueerde unieke PID's' aanmaken. De betekenis van die organisatie code is dan niet automatisch 'owner' van het individu maar slechts de initiator van het PID...

👍 Dit zou ook mijn voorkeur hebben

**Comment by StichtingRIONED** [comment]
Bedankt Niels, Redmer. We hebben jullie ideeën meegenomen in de laatste update.
